// USER
export const SET_USER = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const SET_CONTACTS = 'SET_CONTACTS';
export const USER_ERROR = 'USER_ERROR';
export const SET_LOADING = 'SET_LOADING';

// LAYOUT
export const SET_FORM_INDEX = 'SET_FORM_INDEX';
export const SET_REDIRECT = 'SET_REDIRECT';

// CONVERSATION
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';